### PR TITLE
Enable support for autoconfirming users

### PR DESCRIPTION
**Pull request by moshekaplan**
Enables support for autoconfirming users.

This is an especially useful feature for when the user is subscribing to receive text messages on a cell phone without Internet access, and so are unable to click on the confirm link.

### CODE REVIEW

**Comment by michield** [comment]
I prefer not to have this in core. It's not something I can offer in the hosted service. But it can be done in plugins, like https://github.com/michield/phplist-plugin-listcleaner

**Comment by moshekaplan** [comment]
Could this be made into a 'hidden' configuration value on the hosted version, that hosted lists would not be able to access?

**Comment by michield** [comment]
well, that's handled with plugins. Currently hosted does not have plugins at all (apart from the editor) and I'm working to offer selected plugins. The listcleaner one would not be one of them.

plugins allow download users to pick-n-mix their functionality.

**Comment by moshekaplan** [comment]
Understood. I looked at the plugin - it would still send an email to any newly-registered emails, asking them to confirm, which could be confusing for them, especially if they don't need to.

It sounds like there's a bigger issue at hand: It sounds like one of the goals is to avoid adding any code to the core that you don't want in the hosted version. I agree that plugins are especially useful for that. But plugins cannot do everything, simply because there aren't hooks to allow controlling everything.

**Comment by michield** [comment]
Yes, I'm trying to concentrate on simply adding more plugin-hooks to core. In fact, I've even taken core functionality out, in order to move it to plugins. That allows for more flexible extending.

**Comment by moshekaplan** [comment]
So perhaps it's worth creating a plugin hook for an `onSubscribe` function that enables controlling what occurs when a user subscribes, rather than just hooking specific parts of the page would be best? It would likely require refactoring some of the existing code in `subscribelib2.php` so it's more accessible to a plugin.

**Comment by michield** [comment]
I'm happy for any hooks to be added. But in this case, you can also just change the content of the "Request for confirmation" email to be similar to the "Welcome" one. In that case the subscriber receives a welcome email without the confirmation URL and is confirmed automatically.

**Comment by moshekaplan** [comment]
You're correct - I thought of that too. It just seems very... hackish.

**Comment by michield** [comment]
Well, if there's a place to configure it, it's not a hack in my view. It's a particular configuration. Maybe the plugin can do it for you, to make it less of a hack :-)

**Pull request closed without merging**
